- src/routes/+layout.svelte
- src/routes/+page.svelte
- src/routes/about/+page.svelte
- src/routes/others/[slug]/+page.svelte
- src/routes/prof/+page.svelte
Reverts IshaanAdarsh/ezmail#29
> Revert "hack"

- README.md
- src/routes/+page.svelte
- static/favicon.png:Zone.Identifier
Hey @IshaanAdarsh 
I have completed the task and made one fix in readme that I noticed. Kindly review it and if there are any changes do let me know. And if everything is fine kindly accept the request. Also the file with : in its name is deleted kindly add it again from your side
Thank you
> made features section responsive and updated readme

- src/routes/+layout.svelte
fixes #13
- Identified all the broken links on the website and fixed them
@IshaanAdarsh Let me know if I missed anything. Thanks!
> Fixed broken links

- Content/Email to Administration.md
- Content/To Professor.md
- src/routes/+page.svelte
- src/routes/about/+page.svelte
- src/routes/admin/data.js
Fixed all the typos I could find in the code base. Would be happy to help if i missed something.
(For reference, I checked [Oxford Dictionary](https://www.oxfordlearnersdictionaries.com/definition/english/bona-fide) for the correct spelling of bona fide, but if you prefer bonafied, I can revert it back.)
> Fixed typos

- src/routes/+layout.svelte
Hey @IshaanAdarsh
I have completed the task and improved the Hamburger Menu. Kindly review it and if there are any changes do let me know. If everything is good kindly accept the request. 
issue: #28 
https://github.com/IshaanAdarsh/ezmail/assets/93966956/e5d7e536-610e-44eb-8d7c-afabfe4c2d3d
> Hamburger menu improved #28

- src/routes/+page.svelte
-  I have  followed the guidelines stated in [README.md].
- I have ensured that there aren't any other open [Pull Requests].
a. Changed logo of twitter
b. I have changed the logo of twitter to X logo.
> Changed the twitter logo to X logo

- Content/Email to Administration.md
- Content/To Alumni.md
- Content/To Professor.md
> Templates Added #6

- package-lock.json
- src/routes/+page.svelte
Yes
Yes
Contact us page is added
`closes #17`
> Contact us page added

- src/routes/+layout.svelte
Yes
Yes
Made changes to hamburger menu UI to match website design
`closes #45`
> Suitable changes made to hamburger menu

- src/routes/+page.svelte
- [√ ] Have you followed the guidelines stated in [README.md](https://github.com/IshaanAdarsh/ezmail/tree/main#how-to-contribute) file?
- [ √] Have you checked to ensure there aren't any other open [Pull Requests](https://github.com/IshaanAdarsh/ezmail/pulls) for the desired changed?
- [ √ ] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [ × ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ × ] This change requires a documentation update
Set Responsiveness of our team Section.
c. Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes …
> [Fixes #24] Set Responsiveness of our team section.

- package-lock.json
- package.json
- src/routes/about/+page.svelte
Hey @IshaanAdarsh 
Sorry for the delay. I have completed the task #21, kindly review it and if there are any changes then do let me know. And if not then kindly accept the request
Thank you
> added contributors section in about page

- src/routes/+layout.svelte
- [X ] Have you followed the guidelines stated in [README.md](https://github.com/IshaanAdarsh/ezmail/tree/main#how-to-contribute) file?
- [X ] Have you checked to ensure there aren't any other open [Pull Requests](https://github.com/IshaanAdarsh/ezmail/pulls) for the desired changed?
- [ X] Bug fix (non-breaking change which fixes an issue)
Fixes #82 
This PR fixes the problem exist in bottom logo image
Before this change website look like
After the changes
> Fix: Bottom logo image problem

- src/app.css
- src/app.html
- src/routes/+layout.svelte
> Issue #11: Integrated google translation API to translate website content

- src/routes/+layout.svelte
> fixed footer link alignments

- src/routes/+layout.svelte
- src/routes/+page.svelte
- src/routes/about/+page.svelte
> Separate route for Contact Us

- src/routes/+layout.svelte
> enhanced the footer section to a new look

- .github/workflows/performance-test.yml
- package-lock.json
- package.json
- testScripts/performance-test.js
> [Fixes #10] Cross-Browser-Testing

- src/routes/+layout.svelte
- [FIX - 99] - Fix broken "To Administration" link
- Fixed the broken "To Administration" link from "admn" to "admin".
closes #99
> [FIX - 99] - Fix broken "To Administration" link

- src/routes/+layout.svelte
> Modified the link for About in the footer

- src/app.css
- src/routes/login/+page.svelte
- src/routes/signin/+page.svelte
This pr is about redesigning both sign-in and sign-up pages for the better user flow and user experience. Both pages are now responsive to various screen sizes.
- changed css
- changed some of the wordings (i.e. sign in -> sign up)
- added a new method which clears the user input when error occurs
This pr will close #112
> UI Enhancement on sign-in and sign-up pages

- src/routes/admin/[slug]/+page.svelte
- src/routes/others/[slug]/+page.svelte
Fixes #117 
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
This Pull request fixes the issue of wrong text alignment.
> fixes-issues #117

- .github/workflows/performance-test.yml
- [y] Have you followed the guidelines stated in [README.md](https://github.com/IshaanAdarsh/ezmail/tree/main#how-to-contribute) file?
- [y] Have you checked to ensure there aren't any other open [Pull Requests](https://github.com/IshaanAdarsh/ezmail/pulls) for the desired changed?
- [✓] Breaking change (fix or feature that would cause existing functionality to not work as expected)
> Removed Responsiveness Check Test as it's failing.

- src/routes/login/+page.svelte
Corrected the dimensions of the login section
Fixes #120 
I have rectified the dimensions of the login section and its responsiveness.
> FIX:The dimensions of the login section

- src/routes/+page.svelte
- Ishaan's avatar image link was broken, replaces that with his img from github
- added an `onerror` tag to the image tag to load an alt image when the src file doesnt load
updated img
our team section if the images don't load
> changes ishaan's avatar's src in img tag

- src/routes/about/+page.svelte
- [yes ] Have you followed the guidelines stated in [README.md](https://github.com/IshaanAdarsh/ezmail/tree/main#how-to-contribute) file?
- [ yes] Have you checked to ensure there aren't any other open [Pull Requests](https://github.com/IshaanAdarsh/ezmail/pulls) for the desired changed?
Issue number #124  is solved 
I have enhanced UI of About Us Section on the website.
> Enhance UI of About Us Section on the website

- src/routes/signin/+page.svelte
Fixed issue #133 .
- [ x] Have you followed the guidelines stated in [README.md](https://github.com/IshaanAdarsh/ezmail/tree/main#how-to-contribute) file?
- [x ] Have you checked to ensure there aren't any other open [Pull Requests](https://github.com/IshaanAdarsh/ezmail/pulls) for the desired changed?
- [ x] Bug fix (non-breaking change which fixes an issue)
> Added margin to the Sign Up Header

- src/app.css
- src/routes/login/+page.svelte
- src/routes/signin/+page.svelte
- [√ ] Have you followed the guidelines stated in [README.md](https://github.com/IshaanAdarsh/ezmail/tree/main#how-to-contribute) file?
- [ √] Have you checked to ensure there aren't any other open [Pull Requests](https://github.com/IshaanAdarsh/ezmail/pulls) for the desired changed?
- [√ ] New feature (non-breaking change which adds functionality)
closes #113 #131  #132
> Revamped Signup and Signin Page

- package-lock.json
- package.json
- src/routes/prof/[slug]/+page.svelte
- static/copy.svg
- static/tick.svg
> added copy-to-clipboard functionality
